name: Deploy Tiddlywiki To Github Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'

      - name: Install Dependency
        run: npm install
      - name: Build
        run: npm start

      - uses: montudor/action-zip
        with:
          args: zip -qq -r Kenan-Modpack-Mod合集汉化版.zip Kenan-Modpack-汉化版/
      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: 'latest'
          prerelease: false
          title: '最新CDDA-Kenan-Mod合集汉化版'
          files: |
            Kenan-Modpack-Mod合集汉化版.zip
