name: PR Voting Automerge
on:
  pull_request_target:
    types: [opened, synchronize, reopened, closed]

jobs:
  democracy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Counting Vote
        uses: myyk/git-democracy@v1
